name: hi
channels:
  - defaults
dependencies:
  - conda=4.12.0
  - conda-package-handling=1.8.1
  - pip=21.2.4
  - python=3.9.5
  - tqdm=4.63.0
  - pip:
    - gym==0.17.2
    - jupyter==1.0.0
    - matplotlib==3.3.1
    - mbrl==0.1.5
    - mujoco-py==2.1.2.14
    - numpy
    - scipy==1.8.0
    - tensorboard==2.8.0
    - torch==1.10.2
    - torchaudio==0.10.2
    - torchvision==0.11.3
    - torchviz==0.0.2
    - protobuf==3.20.*
    - pybullet
    - quadprog
